version: '3'
services:
  descalzo:
    image: webdevops/php-nginx:8.3
    depends_on:
      - descalzo-db
    container_name: descalzo
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ssh:/home/application/.ssh:ro
      - ./docker/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    environment:
      - DB_URL=mysql://user:secret@descalzo-db/descalzo_db
    ports:
      - "8299:80"

  descalzo-db:
    image: mysql:latest
    container_name: descalzo-db
    volumes:
      - ./docker/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/db_data:/var/lib/mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    ports:
      - "8207:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: descalzo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
